export const actionTypes = {
  // 
  ALL_PRODUCT_REQUEST: "ALL_PRODUCT_REQUEST",
  ALL_PRODUCT_SUCCESS: "ALL_PRODUCT_SUCCESS",
  ALL_PRODUCT_FAIL: "ALL_PRODUCT_FAIL",
  
  // singel product action types
  PRODUCT_REQUEST: "PRODUCT_REQUEST",
  PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
  PRODUCT_FAIL: "PRODUCT_FAIL",


  CLEAR_ERROR: "CLEAR_ERROR",
};
